#include <iostream>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <iterator>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstring>
#include <ctime>
#include <string>
#include <algorithm>
#include <map>
#include <set>
#include <vector>
#include <queue>
#include <bitset>
#include <cctype>
#include <cassert>
#include <complex>

class NOlow2high{};
class NOtype{};
class DtrNOzero{};
class NOdivzero{};
class Ag2many{};
class Ag2less{};
class FirW{};
class SecW{};
class SecNOzero{};
class NOallInt{};
class NOCrQ2Q{};
class NOCp2R{};
class TkExp{};
class NOcpCMP{};
class NOOp{};
class NOaOp{};
class NOfitBkt{};
class NaN{};
class InvldExp{};
class OnlyInt{};
class LkAg{};
class TypeW{};
class OnlyE_NN_Int{};
class IdxW{};
class NOChar{};
class NOallZero{};
class NOFile{};
